# Major Survey Results Project 1 Part 2- Mitra Iyer - 10/7/25

## This is project shows the information about the data frame detailing student responses on the student life, classes, and more at CCM. The first part gives information about the data frame and the second part cleans the data frame to answer my data science questions and remove uneccessary values.

#### import pandas

In [36]:
import pandas as pd

#### read in csv

In [37]:
data = pd.read_csv('MajorsSurveyResults24.csv')

#### describes data

In [38]:
data.describe()

       On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you in taking more computing classes?
count                                          62.000000
mean                                            3.580645
std                                             1.079593
min                                             1.000000
25%                                             3.000000
50%                                             4.000000
75%                                             4.000000
max                                             5.000000

#### returns all the columns

In [39]:
data.columns

Index(['Timestamp', 'Which course are you enrolled in?',
       'How did you hear about County College of Morris? [CCM Web site]',
       'How did you hear about County College of Morris? [Social Media]',
       'How did you hear about County College of Morris? [Community Event]',
       'How did you hear about County College of Morris? [Family member or friend]',
       'How did you hear about County College of Morris? [Current CCM student]',
       'How did you hear about County College of Morris? [CCM Alumni]',
       'How did you hear about County College of Morris? [High School Teacher]',
       'How did you hear about County College of Morris? [High School Counselor]',
       'How did you hear about County College of Morris? [In-app advertisement]',
       'How did you hear about County College of Morris? [Employer]',
       'How did you hear about County College of Morris? [Billboard]',
       'How did you hear about County College of Morris? [Television]',
       'How did you hear about County College of Morris? [Radio]',
       'How did you hear about County College of Morris? [Other]',
       'To what extent did the following impact your decision to attend County College of Morris? [Affordable cost]',
       'To what extent did the following impact your decision to attend County College of Morris? [Location/convenience]',
       'To what extent did the following impact your decision to attend County College of Morris? [Choice of programs]',
       'To what extent did the following impact your decision to attend County College of Morris? [Online offerings]',
       'To what extent did the following impact your decision to attend County College of Morris? [Family/friend referral]',
       'To what extent did the following impact your decision to attend County College of Morris? [Faculty/staff]',
       'To what extent did the following impact your decision to attend County College of Morris? [College reputation]',
       'To what extent did the following impact your decision to attend County College of Morris? [Financial Aid]',
       'To what extent did the following impact your decision to attend County College of Morris? [Scholarships]',
       'To what extent did the following impact your decision to attend County College of Morris? [Small class sizes]',
       'To what extent did the following impact your decision to attend County College of Morris? [Extra-curricular opportunities]',
       'To what extent did the following impact your decision to attend County College of Morris? [Accepted my transfer credits]',
       'To what extent did the following impact your decision to attend County College of Morris? [Negative experience at another college]',
       'To what extent did the following impact your decision to attend County College of Morris? [NJ Stars Program]',
       'To what extent did the following impact your decision to attend County College of Morris? [Ability to transfer CCM credits to a 4-year school]',
       'To what extent did the following impact your decision to attend County College of Morris? [Get college credit while in high school]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Open House]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Instant Decision Day]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [On-Campus Information Session]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Titans Tuesday (Virtual) Information Session]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Women Who Dare]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Regional College Fair]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [HS Sharetime Information Session]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Challenger Program]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [CyberSecurity Information Protection Program Participation ]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Information Session at my high school]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Campus Visit with my high school]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Campus Visit (individual)]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Workforce Development class]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Corporate Training]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Teen Arts Festival]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Summer camp at CCM]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing class]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing related club]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Computing-related competitions (e.g., Robotics competition, Lego competition, Cybersecurity, Programming)]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Afterschool computing-related camp/program]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Summer computing related camp/program]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [An AP computing class]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [A dual enrollment computing class]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend influence]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend working in the computing field]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [High school teacher or guidance counselor]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Employer influence]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Current CCM student]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Experience at work]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Other]',
       'What degree program are you currently enrolled in?',
       'What motivated you to seek a computing degree/certificate at CCM?  [To get a job in the computing field]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Transfer to bachelor's level program]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Transfer credits back to HS degree (ShareTime, Challenger Program)]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Career Advancement]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Career Change]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Professional Development]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Job Displacement]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Relocation]',
       'What motivated you to seek a computing degree/certificate at CCM?  [To keep current in tech industry]',
       'What motivated you to seek a computing degree/certificate at CCM?  [IT Industry Certifications]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Financial]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Personal Enrichment]',
       'Did you receive information about the CCM computing programs from any of the following sources? [High school guidance counselor]',
       'Did you receive information about the CCM computing programs from any of the following sources? [High School Teacher]',
       'Did you receive information about the CCM computing programs from any of the following sources? [CCM Information Technologies Website]',
       'Did you receive information about the CCM computing programs from any of the following sources? [CCM Admissions]',
       'Did you receive information about the CCM computing programs from any of the following sources? [CCM advisor/counselor]',
       'Did you receive information about the CCM computing programs from any of the following sources? [Employer]',
       'Did you receive information about the CCM computing programs from any of the following sources? [CCM Workforce Development]',
       'Did you receive information about the CCM computing programs from any of the following sources? [NJ Workforce Development Program]',
       'Did you receive information about the CCM computing programs from any of the following sources? [Other]',
       'Was a computing major/certificate your first choice, or did you change majors from a different CCM program? If you changed majors, indicate what your first major was.',
       'On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you in taking more computing classes?',
       'Please explain your answer to the question above.  Why or why not would you be interested in taking another computing class?',
       'Gender', 'Race/ethnicity', 'Age '],
      dtype='object')

#### returns the width/length of data

In [40]:
data.shape

(197, 90)

#### returns all the data types

In [41]:
data.dtypes

Timestamp                                                                                                                                               object
Which course are you enrolled in?                                                                                                                       object
How did you hear about County College of Morris? [CCM Web site]                                                                                         object
How did you hear about County College of Morris? [Social Media]                                                                                         object
How did you hear about County College of Morris? [Community Event]                                                                                      object
                                                                                                                                                        ...
On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you in taking more computing classes?    float64
Please explain your answer to the question above.  Why or why not would you be interested in taking another computing class?                            object
Gender                                                                                                                                                  object
Race/ethnicity                                                                                                                                          object
Age                                                                                                                                                     object
Length: 90, dtype: object

#### returns top rows of the data set

In [42]:
data.head()

,Timestamp,Which course are you enrolled in?,How did you hear about County College of Morris? [CCM Web site],How did you hear about County College of Morris? [Social Media],How did you hear about County College of Morris? [Community Event],How did you hear about County College of Morris? [Family member or friend],How did you hear about County College of Morris? [Current CCM student],How did you hear about County College of Morris? [CCM Alumni],How did you hear about County College of Morris? [High School Teacher],How did you hear about County College of Morris? [High School Counselor],...,Did you receive information about the CCM computing programs from any of the following sources? [Employer],Did you receive information about the CCM computing programs from any of the following sources? [CCM Workforce Development],Did you receive information about the CCM computing programs from any of the following sources? [NJ Workforce Development Program],Did you receive information about the CCM computing programs from any of the following sources? [Other],"Was a computing major/certificate your first choice, or did you change majors from a different CCM program? If you changed majors, indicate what your first major was.","On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you in taking more computing classes?",Please explain your answer to the question above. Why or why not would you be interested in taking another computing class?,Gender,Race/ethnicity,Age
0,2024/09/09 12:33:58 PM AST,CMP 128 Computer Science I,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,...,NaN,NaN,NaN,NaN,NaN,2.0,Quite difficult and I do not see myself using ...,Man,White/Caucasian,21-24
1,2024/09/09 6:00:11 PM AST,NaN,No,No,Yes,No,No,No,Yes,Don't recall,...,No,No,No,Don't recall,First Choice,NaN,NaN,Man,Hispanic or Latino;White/Caucasian;Multi-Racial,18 and younger
2,2024/09/10 9:00:12 AM AST,CMP 128 Computer Science I,No,No,No,Yes,No,Yes,No,Yes,...,No,No,No,No,First Choice,NaN,NaN,Man,Hispanic or Latino;Asian,18 and younger
3,2024/09/10 12:34:53 PM AST,CMP 128 Computer Science I,Yes,Yes,Yes,Yes,No,No,Yes,Yes,...,NaN,NaN,NaN,NaN,NaN,3.0,It all depends on what classes are required fo...,Man,Hispanic or Latino,19-20
4,2024/09/10 3:06:47 PM AST,CMP 128 Computer Science I,No,No,No,Yes,No,No,Yes,No,...,Yes,No,No,Yes,First Choice,NaN,NaN,Man,Asian,19-20

#### returns bottom rows of data set

In [43]:
data.tail()

,Timestamp,Which course are you enrolled in?,How did you hear about County College of Morris? [CCM Web site],How did you hear about County College of Morris? [Social Media],How did you hear about County College of Morris? [Community Event],How did you hear about County College of Morris? [Family member or friend],How did you hear about County College of Morris? [Current CCM student],How did you hear about County College of Morris? [CCM Alumni],How did you hear about County College of Morris? [High School Teacher],How did you hear about County College of Morris? [High School Counselor],...,Did you receive information about the CCM computing programs from any of the following sources? [Employer],Did you receive information about the CCM computing programs from any of the following sources? [CCM Workforce Development],Did you receive information about the CCM computing programs from any of the following sources? [NJ Workforce Development Program],Did you receive information about the CCM computing programs from any of the following sources? [Other],"Was a computing major/certificate your first choice, or did you change majors from a different CCM program? If you changed majors, indicate what your first major was.","On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you in taking more computing classes?",Please explain your answer to the question above. Why or why not would you be interested in taking another computing class?,Gender,Race/ethnicity,Age
192,2024/09/22 6:32:46 PM AST,CMP 128 Computer Science I,Don't recall,Don't recall,Don't recall,Don't recall,Yes,Don't recall,Don't recall,Don't recall,...,No,No,No,No,First Choice,NaN,NaN,Man,Black/African American,19-20
193,2024/09/22 8:51:18 PM AST,CMP 128 Computer Science I,Yes,No,No,Yes,No,No,No,Yes,...,Don't recall,Don't recall,Don't recall,Don't recall,Science,NaN,NaN,Man,Hispanic or Latino;Black/African American,19-20
194,2024/09/22 9:17:23 PM AST,CMP 128 Computer Science I,Yes,Don't recall,No,No,No,No,Yes,Yes,...,No,No,No,No,Business,NaN,NaN,Man,Hispanic or Latino,19-20
195,2024/09/22 11:07:28 PM AST,CMP 128 Computer Science I,Yes,No,No,Yes,Yes,Yes,Yes,No,...,Don't recall,Don't recall,Don't recall,Don't recall,Engineering,NaN,NaN,Man,Hispanic or Latino;American Indian/Native Amer...,19-20
196,2024/09/27 1:01:23 PM AST,CMP 131 Fundamentals of Programming (Python),No,No,No,Yes,Yes,Yes,No,No,...,Yes,Yes,Yes,No,First Choice,NaN,NaN,Man,White/Caucasian,25-34

#### returns random sample of items

In [44]:
data.sample()

,Timestamp,Which course are you enrolled in?,How did you hear about County College of Morris? [CCM Web site],How did you hear about County College of Morris? [Social Media],How did you hear about County College of Morris? [Community Event],How did you hear about County College of Morris? [Family member or friend],How did you hear about County College of Morris? [Current CCM student],How did you hear about County College of Morris? [CCM Alumni],How did you hear about County College of Morris? [High School Teacher],How did you hear about County College of Morris? [High School Counselor],...,Did you receive information about the CCM computing programs from any of the following sources? [Employer],Did you receive information about the CCM computing programs from any of the following sources? [CCM Workforce Development],Did you receive information about the CCM computing programs from any of the following sources? [NJ Workforce Development Program],Did you receive information about the CCM computing programs from any of the following sources? [Other],"Was a computing major/certificate your first choice, or did you change majors from a different CCM program? If you changed majors, indicate what your first major was.","On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you in taking more computing classes?",Please explain your answer to the question above. Why or why not would you be interested in taking another computing class?,Gender,Race/ethnicity,Age
172,2024/09/16 9:56:07 AM AST,CMP 128 Computer Science I,Yes,No,No,Yes,No,No,No,No,...,NaN,NaN,NaN,NaN,NaN,4.0,"Coding can be interesting, I'm just not good a...",Man,Hispanic or Latino;Black/African American;Whit...,19-20

#### returns summary of dataframe

In [45]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 197 entries, 0 to 196
Data columns (total 90 columns):
 #   Column                                                                                                                                                                                                                                                           Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                                           --------------  -----
 0   Timestamp                                                                                                                                                                                                                                                        197 non-null    object
 1   Which course are you enrolled in?                                                                                                                                                                                                                                195 non-null    object
 2   How did you hear about County College of Morris? [CCM Web site]                                                                                                                                                                                                  197 non-null    object
 3   How did you hear about County College of Morris? [Social Media]                                                                                                                                                                                                  197 non-null    object
 4   How did you hear about County College of Morris? [Community Event]                                                                                                                                                                                               197 non-null    object
 5   How did you hear about County College of Morris? [Family member or friend]                                                                                                                                                                                       197 non-null    object
 6   How did you hear about County College of Morris? [Current CCM student]                                                                                                                                                                                           197 non-null    object
 7   How did you hear about County College of Morris? [CCM Alumni]                                                                                                                                                                                                    197 non-null    object
 8   How did you hear about County College of Morris? [High School Teacher]                                                                                                                                                                                           197 non-null    object
 9   How did you hear about County College of Morris? [High School Counselor]                                                                                                                                                                                         197 non-null    object
 10  How did you hear about County College of Morris? [In-app advertisement]                                                                                                                                                                                          197 non-null    object
 11  How did you hear about County College of Morris? [Employer]                                                                                                                                                                                                      197 non-null    object
 12  How did you hear about County College of Morris? [Billboard]                                                                                                                                                                                                     197 non-null    object
 13  How did you hear about County College of Morris? [Television]                                                                                                                                                                                                    197 non-null    object
 14  How did you hear about County College of Morris? [Radio]                                                                                                                                                                                                         197 non-null    object
 15  How did you hear about County College of Morris? [Other]                                                                                                                                                                                                         197 non-null    object
 16  To what extent did the following impact your decision to attend County College of Morris? [Affordable cost]                                                                                                                                                      192 non-null    object
 17  To what extent did the following impact your decision to attend County College of Morris? [Location/convenience]                                                                                                                                                 192 non-null    object
 18  To what extent did the following impact your decision to attend County College of Morris? [Choice of programs]                                                                                                                                                   192 non-null    object
 19  To what extent did the following impact your decision to attend County College of Morris? [Online offerings]                                                                                                                                                     184 non-null    object
 20  To what extent did the following impact your decision to attend County College of Morris? [Family/friend referral]                                                                                                                                               182 non-null    object
 21  To what extent did the following impact your decision to attend County College of Morris? [Faculty/staff]                                                                                                                                                        177 non-null    object
 22  To what extent did the following impact your decision to attend County College of Morris? [College reputation]                                                                                                                                                   186 non-null    object
 23  To what extent did the following impact your decision to attend County College of Morris? [Financial Aid]                                                                                                                                                        180 non-null    object
 24  To what extent did the following impact your decision to attend County College of Morris? [Scholarships]                                                                                                                                                         177 non-null    object
 25  To what extent did the following impact your decision to attend County College of Morris? [Small class sizes]                                                                                                                                                    183 non-null    object
 26  To what extent did the following impact your decision to attend County College of Morris? [Extra-curricular opportunities]                                                                                                                                       176 non-null    object
 27  To what extent did the following impact your decision to attend County College of Morris? [Accepted my transfer credits]                                                                                                                                         162 non-null    object
 28  To what extent did the following impact your decision to attend County College of Morris? [Negative experience at another college]                                                                                                                               153 non-null    object
 29  To what extent did the following impact your decision to attend County College of Morris? [NJ Stars Program]                                                                                                                                                     151 non-null    object
 30  To what extent did the following impact your decision to attend County College of Morris? [Ability to transfer CCM credits to a 4-year school]                                                                                                                   185 non-null    object
 31  To what extent did the following impact your decision to attend County College of Morris? [Get college credit while in high school]                                                                                                                              163 non-null    object
 32  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Open House]                                                   197 non-null    object
 33  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Instant Decision Day]                                         197 non-null    object
 34  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [On-Campus Information Session]                                197 non-null    object
 35  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Titans Tuesday (Virtual) Information Session]                 197 non-null    object
 36  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Women Who Dare]                                               197 non-null    object
 37  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Regional College Fair]                                        197 non-null    object
 38  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [HS Sharetime Information Session]                             197 non-null    object
 39  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Challenger Program]                                           197 non-null    object
 40  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [CyberSecurity Information Protection Program Participation ]  197 non-null    object
 41  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Information Session at my high school]                        197 non-null    object
 42  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Campus Visit with my high school]                             197 non-null    object
 43  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Campus Visit (individual)]                                    197 non-null    object
 44  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Workforce Development class]                                  197 non-null    object
 45  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Corporate Training]                                           197 non-null    object
 46  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Teen Arts Festival]                                           197 non-null    object
 47  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Summer camp at CCM]                                           197 non-null    object
 48  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing class]                                                                                                     180 non-null    object
 49  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing related club]                                                                                              167 non-null    object
 50  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Computing-related competitions (e.g., Robotics competition, Lego competition, Cybersecurity, Programming)]                              167 non-null    object
 51  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Afterschool computing-related camp/program]                                                                                             161 non-null    object
 52  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Summer computing related camp/program]                                                                                                  162 non-null    object
 53  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [An AP computing class]                                                                                                                  165 non-null    object
 54  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [A dual enrollment computing class]                                                                                                      164 non-null    object
 55  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend influence]                                                                                                             178 non-null    object
 56  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend working in the computing field]                                                                                        170 non-null    object
 57  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [High school teacher or guidance counselor]                                                                                              166 non-null    object
 58  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Employer influence]                                                                                                                     164 non-null    object
 59  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Current CCM student]                                                                                                                    164 non-null    object
 60  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Experience at work]                                                                                                                     168 non-null    object
 61  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Other]                                                                                                                                  161 non-null    object
 62  What degree program are you currently enrolled in?                                                                                                                                                                                                               197 non-null    object
 63  What motivated you to seek a computing degree/certificate at CCM?  [To get a job in the computing field]                                                                                                                                                         135 non-null    object
 64  What motivated you to seek a computing degree/certificate at CCM?  [Transfer to bachelor's level program]                                                                                                                                                        135 non-null    object
 65  What motivated you to seek a computing degree/certificate at CCM?  [Transfer credits back to HS degree (ShareTime, Challenger Program)]                                                                                                                          135 non-null    object
 66  What motivated you to seek a computing degree/certificate at CCM?  [Career Advancement]                                                                                                                                                                          135 non-null    object

## Cleaning the Data set

### Purpose of data cleaning: I want to remove the columns I do not need, make them have shorter lowercase names, as well as remove nAn values. This is to answer my questions efficiently which I wrote down below.

### Data Science Questions:
    1. What are the order courses that students enrolled in had the most participants in campus events or activities?
    2. What is the order of majors that havethe most students who were exposed to computing classes in middle or high school?
    3. What are the majors that have the fewest people who identify as a woman?
    4. From which source did the most students receive information about CCM’s computing programs?  Which source did the least students hear information about CCM's computing programs?
    5. Which age group is least represented in computing?

#### Show head of the data before transformations

In [46]:
data.head()

,Timestamp,Which course are you enrolled in?,How did you hear about County College of Morris? [CCM Web site],How did you hear about County College of Morris? [Social Media],How did you hear about County College of Morris? [Community Event],How did you hear about County College of Morris? [Family member or friend],How did you hear about County College of Morris? [Current CCM student],How did you hear about County College of Morris? [CCM Alumni],How did you hear about County College of Morris? [High School Teacher],How did you hear about County College of Morris? [High School Counselor],...,Did you receive information about the CCM computing programs from any of the following sources? [Employer],Did you receive information about the CCM computing programs from any of the following sources? [CCM Workforce Development],Did you receive information about the CCM computing programs from any of the following sources? [NJ Workforce Development Program],Did you receive information about the CCM computing programs from any of the following sources? [Other],"Was a computing major/certificate your first choice, or did you change majors from a different CCM program? If you changed majors, indicate what your first major was.","On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you in taking more computing classes?",Please explain your answer to the question above. Why or why not would you be interested in taking another computing class?,Gender,Race/ethnicity,Age
0,2024/09/09 12:33:58 PM AST,CMP 128 Computer Science I,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,...,NaN,NaN,NaN,NaN,NaN,2.0,Quite difficult and I do not see myself using ...,Man,White/Caucasian,21-24
1,2024/09/09 6:00:11 PM AST,NaN,No,No,Yes,No,No,No,Yes,Don't recall,...,No,No,No,Don't recall,First Choice,NaN,NaN,Man,Hispanic or Latino;White/Caucasian;Multi-Racial,18 and younger
2,2024/09/10 9:00:12 AM AST,CMP 128 Computer Science I,No,No,No,Yes,No,Yes,No,Yes,...,No,No,No,No,First Choice,NaN,NaN,Man,Hispanic or Latino;Asian,18 and younger
3,2024/09/10 12:34:53 PM AST,CMP 128 Computer Science I,Yes,Yes,Yes,Yes,No,No,Yes,Yes,...,NaN,NaN,NaN,NaN,NaN,3.0,It all depends on what classes are required fo...,Man,Hispanic or Latino,19-20
4,2024/09/10 3:06:47 PM AST,CMP 128 Computer Science I,No,No,No,Yes,No,No,Yes,No,...,Yes,No,No,Yes,First Choice,NaN,NaN,Man,Asian,19-20

#### I am printing the tail of the data to show data at the end of the data frame as well

In [47]:
data.tail()

,Timestamp,Which course are you enrolled in?,How did you hear about County College of Morris? [CCM Web site],How did you hear about County College of Morris? [Social Media],How did you hear about County College of Morris? [Community Event],How did you hear about County College of Morris? [Family member or friend],How did you hear about County College of Morris? [Current CCM student],How did you hear about County College of Morris? [CCM Alumni],How did you hear about County College of Morris? [High School Teacher],How did you hear about County College of Morris? [High School Counselor],...,Did you receive information about the CCM computing programs from any of the following sources? [Employer],Did you receive information about the CCM computing programs from any of the following sources? [CCM Workforce Development],Did you receive information about the CCM computing programs from any of the following sources? [NJ Workforce Development Program],Did you receive information about the CCM computing programs from any of the following sources? [Other],"Was a computing major/certificate your first choice, or did you change majors from a different CCM program? If you changed majors, indicate what your first major was.","On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you in taking more computing classes?",Please explain your answer to the question above. Why or why not would you be interested in taking another computing class?,Gender,Race/ethnicity,Age
192,2024/09/22 6:32:46 PM AST,CMP 128 Computer Science I,Don't recall,Don't recall,Don't recall,Don't recall,Yes,Don't recall,Don't recall,Don't recall,...,No,No,No,No,First Choice,NaN,NaN,Man,Black/African American,19-20
193,2024/09/22 8:51:18 PM AST,CMP 128 Computer Science I,Yes,No,No,Yes,No,No,No,Yes,...,Don't recall,Don't recall,Don't recall,Don't recall,Science,NaN,NaN,Man,Hispanic or Latino;Black/African American,19-20
194,2024/09/22 9:17:23 PM AST,CMP 128 Computer Science I,Yes,Don't recall,No,No,No,No,Yes,Yes,...,No,No,No,No,Business,NaN,NaN,Man,Hispanic or Latino,19-20
195,2024/09/22 11:07:28 PM AST,CMP 128 Computer Science I,Yes,No,No,Yes,Yes,Yes,Yes,No,...,Don't recall,Don't recall,Don't recall,Don't recall,Engineering,NaN,NaN,Man,Hispanic or Latino;American Indian/Native Amer...,19-20
196,2024/09/27 1:01:23 PM AST,CMP 131 Fundamentals of Programming (Python),No,No,No,Yes,Yes,Yes,No,No,...,Yes,Yes,Yes,No,First Choice,NaN,NaN,Man,White/Caucasian,25-34

#### Show all the columns so that I am able to see all the names in one place

In [48]:
data.columns

Index(['Timestamp', 'Which course are you enrolled in?',
       'How did you hear about County College of Morris? [CCM Web site]',
       'How did you hear about County College of Morris? [Social Media]',
       'How did you hear about County College of Morris? [Community Event]',
       'How did you hear about County College of Morris? [Family member or friend]',
       'How did you hear about County College of Morris? [Current CCM student]',
       'How did you hear about County College of Morris? [CCM Alumni]',
       'How did you hear about County College of Morris? [High School Teacher]',
       'How did you hear about County College of Morris? [High School Counselor]',
       'How did you hear about County College of Morris? [In-app advertisement]',
       'How did you hear about County College of Morris? [Employer]',
       'How did you hear about County College of Morris? [Billboard]',
       'How did you hear about County College of Morris? [Television]',
       'How did you hear about County College of Morris? [Radio]',
       'How did you hear about County College of Morris? [Other]',
       'To what extent did the following impact your decision to attend County College of Morris? [Affordable cost]',
       'To what extent did the following impact your decision to attend County College of Morris? [Location/convenience]',
       'To what extent did the following impact your decision to attend County College of Morris? [Choice of programs]',
       'To what extent did the following impact your decision to attend County College of Morris? [Online offerings]',
       'To what extent did the following impact your decision to attend County College of Morris? [Family/friend referral]',
       'To what extent did the following impact your decision to attend County College of Morris? [Faculty/staff]',
       'To what extent did the following impact your decision to attend County College of Morris? [College reputation]',
       'To what extent did the following impact your decision to attend County College of Morris? [Financial Aid]',
       'To what extent did the following impact your decision to attend County College of Morris? [Scholarships]',
       'To what extent did the following impact your decision to attend County College of Morris? [Small class sizes]',
       'To what extent did the following impact your decision to attend County College of Morris? [Extra-curricular opportunities]',
       'To what extent did the following impact your decision to attend County College of Morris? [Accepted my transfer credits]',
       'To what extent did the following impact your decision to attend County College of Morris? [Negative experience at another college]',
       'To what extent did the following impact your decision to attend County College of Morris? [NJ Stars Program]',
       'To what extent did the following impact your decision to attend County College of Morris? [Ability to transfer CCM credits to a 4-year school]',
       'To what extent did the following impact your decision to attend County College of Morris? [Get college credit while in high school]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Open House]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Instant Decision Day]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [On-Campus Information Session]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Titans Tuesday (Virtual) Information Session]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Women Who Dare]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Regional College Fair]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [HS Sharetime Information Session]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Challenger Program]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [CyberSecurity Information Protection Program Participation ]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Information Session at my high school]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Campus Visit with my high school]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Campus Visit (individual)]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Workforce Development class]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Corporate Training]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Teen Arts Festival]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Summer camp at CCM]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing class]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing related club]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Computing-related competitions (e.g., Robotics competition, Lego competition, Cybersecurity, Programming)]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Afterschool computing-related camp/program]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Summer computing related camp/program]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [An AP computing class]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [A dual enrollment computing class]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend influence]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend working in the computing field]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [High school teacher or guidance counselor]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Employer influence]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Current CCM student]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Experience at work]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Other]',
       'What degree program are you currently enrolled in?',
       'What motivated you to seek a computing degree/certificate at CCM?  [To get a job in the computing field]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Transfer to bachelor's level program]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Transfer credits back to HS degree (ShareTime, Challenger Program)]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Career Advancement]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Career Change]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Professional Development]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Job Displacement]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Relocation]',
       'What motivated you to seek a computing degree/certificate at CCM?  [To keep current in tech industry]',
       'What motivated you to seek a computing degree/certificate at CCM?  [IT Industry Certifications]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Financial]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Personal Enrichment]',
       'Did you receive information about the CCM computing programs from any of the following sources? [High school guidance counselor]',
       'Did you receive information about the CCM computing programs from any of the following sources? [High School Teacher]',
       'Did you receive information about the CCM computing programs from any of the following sources? [CCM Information Technologies Website]',
       'Did you receive information about the CCM computing programs from any of the following sources? [CCM Admissions]',
       'Did you receive information about the CCM computing programs from any of the following sources? [CCM advisor/counselor]',
       'Did you receive information about the CCM computing programs from any of the following sources? [Employer]',
       'Did you receive information about the CCM computing programs from any of the following sources? [CCM Workforce Development]',
       'Did you receive information about the CCM computing programs from any of the following sources? [NJ Workforce Development Program]',
       'Did you receive information about the CCM computing programs from any of the following sources? [Other]',
       'Was a computing major/certificate your first choice, or did you change majors from a different CCM program? If you changed majors, indicate what your first major was.',
       'On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you in taking more computing classes?',
       'Please explain your answer to the question above.  Why or why not would you be interested in taking another computing class?',
       'Gender', 'Race/ethnicity', 'Age '],
      dtype='object')

#### Find indexes of columns so I can remove them - I created a map that maps the col names to the indexes

In [49]:
col_index_map = {col_name: i for i, col_name in enumerate(data.columns)}

#### Print column names and indexes

In [50]:
col_index_map

{'Timestamp': 0,
 'Which course are you enrolled in?': 1,
 'How did you hear about County College of Morris? [CCM Web site]': 2,
 'How did you hear about County College of Morris? [Social Media]': 3,
 'How did you hear about County College of Morris? [Community Event]': 4,
 'How did you hear about County College of Morris? [Family member or friend]': 5,
 'How did you hear about County College of Morris? [Current CCM student]': 6,
 'How did you hear about County College of Morris? [CCM Alumni]': 7,
 'How did you hear about County College of Morris? [High School Teacher]': 8,
 'How did you hear about County College of Morris? [High School Counselor]': 9,
 'How did you hear about County College of Morris? [In-app advertisement]': 10,
 'How did you hear about County College of Morris? [Employer]': 11,
 'How did you hear about County College of Morris? [Billboard]': 12,
 'How did you hear about County College of Morris? [Television]': 13,
 'How did you hear about County College of Morris? [Radio]': 14,
 'How did you hear about County College of Morris? [Other]': 15,
 'To what extent did the following impact your decision to attend County College of Morris? [Affordable cost]': 16,
 'To what extent did the following impact your decision to attend County College of Morris? [Location/convenience]': 17,
 'To what extent did the following impact your decision to attend County College of Morris? [Choice of programs]': 18,
 'To what extent did the following impact your decision to attend County College of Morris? [Online offerings]': 19,
 'To what extent did the following impact your decision to attend County College of Morris? [Family/friend referral]': 20,
 'To what extent did the following impact your decision to attend County College of Morris? [Faculty/staff]': 21,
 'To what extent did the following impact your decision to attend County College of Morris? [College reputation]': 22,
 'To what extent did the following impact your decision to attend County College of Morris? [Financial Aid]': 23,
 'To what extent did the following impact your decision to attend County College of Morris? [Scholarships]': 24,
 'To what extent did the following impact your decision to attend County College of Morris? [Small class sizes]': 25,
 'To what extent did the following impact your decision to attend County College of Morris? [Extra-curricular opportunities]': 26,
 'To what extent did the following impact your decision to attend County College of Morris? [Accepted my transfer credits]': 27,
 'To what extent did the following impact your decision to attend County College of Morris? [Negative experience at another college]': 28,
 'To what extent did the following impact your decision to attend County College of Morris? [NJ Stars Program]': 29,
 'To what extent did the following impact your decision to attend County College of Morris? [Ability to transfer CCM credits to a 4-year school]': 30,
 'To what extent did the following impact your decision to attend County College of Morris? [Get college credit while in high school]': 31,
 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Open House]': 32,
 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Instant Decision Day]': 33,
 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [On-Campus Information Session]': 34,
 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Titans Tuesday (Virtual) Information Session]': 35,
 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Women Who Dare]': 36,
 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Regional College Fair]': 37,
 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [HS Sharetime Information Session]': 38,
 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Challenger Program]': 39,
 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [CyberSecurity Information Protection Program Participation ]': 40,
 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Information Session at my high school]': 41,
 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Campus Visit with my high school]': 42,
 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Campus Visit (individual)]': 43,
 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Workforce Development class]': 44,
 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Corporate Training]': 45,
 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Teen Arts Festival]': 46,
 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Summer camp at CCM]': 47,
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing class]': 48,
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing related club]': 49,
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Computing-related competitions (e.g., Robotics competition, Lego competition, Cybersecurity, Programming)]': 50,
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Afterschool computing-related camp/program]': 51,
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Summer computing related camp/program]': 52,
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [An AP computing class]': 53,
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [A dual enrollment computing class]': 54,
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend influence]': 55,
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend working in the computing field]': 56,
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [High school teacher or guidance counselor]': 57,
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Employer influence]': 58,
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Current CCM student]': 59,
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Experience at work]': 60,
 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Other]': 61,
 'What degree program are you currently enrolled in?': 62,
 'What motivated you to seek a computing degree/certificate at CCM?  [To get a job in the computing field]': 63,
 "What motivated you to seek a computing degree/certificate at CCM?  [Transfer to bachelor's level program]": 64,
 'What motivated you to seek a computing degree/certificate at CCM?  [Transfer credits back to HS degree (ShareTime, Challenger Program)]': 65,
 'What motivated you to seek a computing degree/certificate at CCM?  [Career Advancement]': 66,
 'What motivated you to seek a computing degree/certificate at CCM?  [Career Change]': 67,
 'What motivated you to seek a computing degree/certificate at CCM?  [Professional Development]': 68,
 'What motivated you to seek a computing degree/certificate at CCM?  [Job Displacement]': 69,
 'What motivated you to seek a computing degree/certificate at CCM?  [Relocation]': 70,
 'What motivated you to seek a computing degree/certificate at CCM?  [To keep current in tech industry]': 71,
 'What motivated you to seek a computing degree/certificate at CCM?  [IT Industry Certifications]': 72,
 'What motivated you to seek a computing degree/certificate at CCM?  [Financial]': 73,
 'What motivated you to seek a computing degree/certificate at CCM?  [Personal Enrichment]': 74,
 'Did you receive information about the CCM computing programs from any of the following sources? [High school guidance counselor]': 75,
 'Did you receive information about the CCM computing programs from any of the following sources? [High School Teacher]': 76,
 'Did you receive information about the CCM computing programs from any of the following sources? [CCM Information Technologies Website]': 77,
 'Did you receive information about the CCM computing programs from any of the following sources? [CCM Admissions]': 78,
 'Did you receive information about the CCM computing programs from any of the following sources? [CCM advisor/counselor]': 79,
 'Did you receive information about the CCM computing programs from any of the following sources? [Employer]': 80,
 'Did you receive information about the CCM computing programs from any of the following sources? [CCM Workforce Development]': 81,
 'Did you receive information about the CCM computing programs from any of the following sources? [NJ Workforce Development Program]': 82,
 'Did you receive information about the CCM computing programs from any of the following sources? [Other]': 83,
 'Was a computing major/certificate your first choice, or did you change majors from a different CCM program? If you changed majors, indicate what your first major was.': 84,
 'On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you in taking more computing classes?': 85,
 'Please explain your answer to the question above.  Why or why not would you be interested in taking another computing class?': 86,
 'Gender': 87,
 'Race/ethnicity': 88,
 'Age ': 89}

#### Remove unneccesary columns based on my questions - I used a list for this and range so I could drop multiple columns

In [51]:
columnsToDrop = list(range(16,32)) + list(range(50,53)) +  list(range(55,62)) + list(range(84,87)) + [88]

In [52]:
data = data.drop(data.columns[columnsToDrop], axis = 1)

In [53]:
data.columns

Index(['Timestamp', 'Which course are you enrolled in?',
       'How did you hear about County College of Morris? [CCM Web site]',
       'How did you hear about County College of Morris? [Social Media]',
       'How did you hear about County College of Morris? [Community Event]',
       'How did you hear about County College of Morris? [Family member or friend]',
       'How did you hear about County College of Morris? [Current CCM student]',
       'How did you hear about County College of Morris? [CCM Alumni]',
       'How did you hear about County College of Morris? [High School Teacher]',
       'How did you hear about County College of Morris? [High School Counselor]',
       'How did you hear about County College of Morris? [In-app advertisement]',
       'How did you hear about County College of Morris? [Employer]',
       'How did you hear about County College of Morris? [Billboard]',
       'How did you hear about County College of Morris? [Television]',
       'How did you hear about County College of Morris? [Radio]',
       'How did you hear about County College of Morris? [Other]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Open House]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Instant Decision Day]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [On-Campus Information Session]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Titans Tuesday (Virtual) Information Session]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Women Who Dare]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Regional College Fair]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [HS Sharetime Information Session]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Challenger Program]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [CyberSecurity Information Protection Program Participation ]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Information Session at my high school]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Campus Visit with my high school]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Campus Visit (individual)]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Workforce Development class]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Corporate Training]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Teen Arts Festival]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Summer camp at CCM]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing class]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing related club]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [An AP computing class]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [A dual enrollment computing class]',
       'What degree program are you currently enrolled in?',
       'What motivated you to seek a computing degree/certificate at CCM?  [To get a job in the computing field]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Transfer to bachelor's level program]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Transfer credits back to HS degree (ShareTime, Challenger Program)]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Career Advancement]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Career Change]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Professional Development]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Job Displacement]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Relocation]',
       'What motivated you to seek a computing degree/certificate at CCM?  [To keep current in tech industry]',
       'What motivated you to seek a computing degree/certificate at CCM?  [IT Industry Certifications]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Financial]',
       'What motivated you to seek a computing degree/certificate at CCM?  [Personal Enrichment]',
       'Did you receive information about the CCM computing programs from any of the following sources? [High school guidance counselor]',
       'Did you receive information about the CCM computing programs from any of the following sources? [High School Teacher]',
       'Did you receive information about the CCM computing programs from any of the following sources? [CCM Information Technologies Website]',
       'Did you receive information about the CCM computing programs from any of the following sources? [CCM Admissions]',
       'Did you receive information about the CCM computing programs from any of the following sources? [CCM advisor/counselor]',
       'Did you receive information about the CCM computing programs from any of the following sources? [Employer]',
       'Did you receive information about the CCM computing programs from any of the following sources? [CCM Workforce Development]',
       'Did you receive information about the CCM computing programs from any of the following sources? [NJ Workforce Development Program]',
       'Did you receive information about the CCM computing programs from any of the following sources? [Other]',
       'Gender', 'Age '],
      dtype='object')

#### Now I am remapping all the column names to make them easier to access

In [54]:
rename_columns = {
    'Timestamp': 'timestamp',
    'Which course are you enrolled in?': 'course_enrolled',
    'How did you hear about County College of Morris? [CCM Web site]': 'hear_ccm_website',
    'How did you hear about County College of Morris? [Social Media]': 'hear_social_media',
    'How did you hear about County College of Morris? [Community Event]': 'hear_community_event',
    'How did you hear about County College of Morris? [Family member or friend]': 'hear_family_friend',
    'How did you hear about County College of Morris? [Current CCM student]': 'hear_current_student',
    'How did you hear about County College of Morris? [CCM Alumni]': 'hear_alumni',
    'How did you hear about County College of Morris? [High School Teacher]': 'hear_hs_teacher',
    'How did you hear about County College of Morris? [High School Counselor]': 'hear_hs_counselor',
    'How did you hear about County College of Morris? [In-app advertisement]': 'hear_inapp_ad',
    'How did you hear about County College of Morris? [Employer]': 'hear_employer',
    'How did you hear about County College of Morris? [Billboard]': 'hear_billboard',
    'How did you hear about County College of Morris? [Television]': 'hear_tv',
    'How did you hear about County College of Morris? [Radio]': 'hear_radio',
    'How did you hear about County College of Morris? [Other]': 'hear_other',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Open House]': 'event_open_house',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Instant Decision Day]': 'event_instant_decision_day',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [On-Campus Information Session]': 'event_oncampus_info_session',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Titans Tuesday (Virtual) Information Session]': 'event_titans_tuesday_virtual',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Women Who Dare]': 'event_women_who_dare',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Regional College Fair]': 'event_college_fair',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [HS Sharetime Information Session]': 'event_hs_sharetime_session',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Challenger Program]': 'event_challenger_program',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [CyberSecurity Information Protection Program Participation ]': 'event_cybersecurity_program',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Information Session at my high school]': 'event_hs_info_session',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Campus Visit with my high school]': 'event_hs_campus_visit',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Campus Visit (individual)]': 'event_individual_campus_visit',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Workforce Development class]': 'event_workforce_class',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Corporate Training]': 'event_corporate_training',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Teen Arts Festival]': "event_teens_arts",
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Summer camp at CCM]': "event_ccm_summer_camp",
    
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing class]': 'impact_hs_computing_class',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing related club]': 'impact_hs_computing_club',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [An AP computing class]': 'impact_ap_computing_class',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [A dual enrollment computing class]': 'impact_dual_enrollment',
    'What degree program are you currently enrolled in?': 'degree_program',
    'What motivated you to seek a computing degree/certificate at CCM?  [To get a job in the computing field]': 'motivation_job',
    'What motivated you to seek a computing degree/certificate at CCM?  [Transfer to bachelor\'s level program]': 'motivation_transfer_bachelors',
    'What motivated you to seek a computing degree/certificate at CCM?  [Transfer credits back to HS degree (ShareTime, Challenger Program)]': 'motivation_transfer_hs',
    'What motivated you to seek a computing degree/certificate at CCM?  [Career Advancement]': 'motivation_career_advancement',
    'What motivated you to seek a computing degree/certificate at CCM?  [Career Change]': 'motivation_career_change',
    'What motivated you to seek a computing degree/certificate at CCM?  [Professional Development]': 'motivation_professional_dev',
    'What motivated you to seek a computing degree/certificate at CCM?  [Job Displacement]': 'motivation_job_displacement',
    'What motivated you to seek a computing degree/certificate at CCM?  [Relocation]': 'motivation_relocation',
    'What motivated you to seek a computing degree/certificate at CCM?  [To keep current in tech industry]': 'motivation_keep_current',
    'What motivated you to seek a computing degree/certificate at CCM?  [IT Industry Certifications]': 'motivation_certifications',
    'What motivated you to seek a computing degree/certificate at CCM?  [Financial]': 'motivation_financial',
    'What motivated you to seek a computing degree/certificate at CCM?  [Personal Enrichment]': 'motivation_enrichment',
    'Did you receive information about the CCM computing programs from any of the following sources? [High school guidance counselor]': 'info_hs_counselor',
    'Did you receive information about the CCM computing programs from any of the following sources? [High School Teacher]': 'info_hs_teacher',
    'Did you receive information about the CCM computing programs from any of the following sources? [Employer]': 'info_employer',
    'Did you receive information about the CCM computing programs from any of the following sources? [CCM Workforce Development]': 'info_ccm_workforce_development',
    'Did you receive information about the CCM computing programs from any of the following sources? [CCM advisor/counselor]' : 'info_ccm_advisor',
    'Did you receive information about the CCM computing programs from any of the following sources? [CCM Information Technologies Website]': 'info_ccm_website',
    'Did you receive information about the CCM computing programs from any of the following sources? [CCM Admissions]': 'info_ccm_admissions',
    'Did you receive information about the CCM computing programs from any of the following sources? [NJ Workforce Development Program]' : 'info_nj_workforce_development',
    'Did you receive information about the CCM computing programs from any of the following sources? [Other]' : 'info.other',
    'Age ': 'age',
    'Gender': 'gender'
}

In [55]:
data = data.rename(columns=rename_columns)

In [56]:
data.columns

Index(['timestamp', 'course_enrolled', 'hear_ccm_website', 'hear_social_media',
       'hear_community_event', 'hear_family_friend', 'hear_current_student',
       'hear_alumni', 'hear_hs_teacher', 'hear_hs_counselor', 'hear_inapp_ad',
       'hear_employer', 'hear_billboard', 'hear_tv', 'hear_radio',
       'hear_other', 'event_open_house', 'event_instant_decision_day',
       'event_oncampus_info_session', 'event_titans_tuesday_virtual',
       'event_women_who_dare', 'event_college_fair',
       'event_hs_sharetime_session', 'event_challenger_program',
       'event_cybersecurity_program', 'event_hs_info_session',
       'event_hs_campus_visit', 'event_individual_campus_visit',
       'event_workforce_class', 'event_corporate_training', 'event_teens_arts',
       'event_ccm_summer_camp', 'impact_hs_computing_class',
       'impact_hs_computing_club', 'impact_ap_computing_class',
       'impact_dual_enrollment', 'degree_program', 'motivation_job',
       'motivation_transfer_bachelors', 'motivation_transfer_hs',
       'motivation_career_advancement', 'motivation_career_change',
       'motivation_professional_dev', 'motivation_job_displacement',
       'motivation_relocation', 'motivation_keep_current',
       'motivation_certifications', 'motivation_financial',
       'motivation_enrichment', 'info_hs_counselor', 'info_hs_teacher',
       'info_ccm_website', 'info_ccm_admissions', 'info_ccm_advisor',
       'info_employer', 'info_ccm_workforce_development',
       'info_nj_workforce_development', 'info.other', 'gender', 'age'],
      dtype='object')

In [57]:
data.head()

,timestamp,course_enrolled,hear_ccm_website,hear_social_media,hear_community_event,hear_family_friend,hear_current_student,hear_alumni,hear_hs_teacher,hear_hs_counselor,...,info_hs_teacher,info_ccm_website,info_ccm_admissions,info_ccm_advisor,info_employer,info_ccm_workforce_development,info_nj_workforce_development,info.other,gender,age
0,2024/09/09 12:33:58 PM AST,CMP 128 Computer Science I,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Man,21-24
1,2024/09/09 6:00:11 PM AST,NaN,No,No,Yes,No,No,No,Yes,Don't recall,...,Don't recall,No,No,No,No,No,No,Don't recall,Man,18 and younger
2,2024/09/10 9:00:12 AM AST,CMP 128 Computer Science I,No,No,No,Yes,No,Yes,No,Yes,...,No,No,Yes,No,No,No,No,No,Man,18 and younger
3,2024/09/10 12:34:53 PM AST,CMP 128 Computer Science I,Yes,Yes,Yes,Yes,No,No,Yes,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Man,19-20
4,2024/09/10 3:06:47 PM AST,CMP 128 Computer Science I,No,No,No,Yes,No,No,Yes,No,...,Don't recall,No,No,No,Yes,No,No,Yes,Man,19-20

In [58]:
data.columns

Index(['timestamp', 'course_enrolled', 'hear_ccm_website', 'hear_social_media',
       'hear_community_event', 'hear_family_friend', 'hear_current_student',
       'hear_alumni', 'hear_hs_teacher', 'hear_hs_counselor', 'hear_inapp_ad',
       'hear_employer', 'hear_billboard', 'hear_tv', 'hear_radio',
       'hear_other', 'event_open_house', 'event_instant_decision_day',
       'event_oncampus_info_session', 'event_titans_tuesday_virtual',
       'event_women_who_dare', 'event_college_fair',
       'event_hs_sharetime_session', 'event_challenger_program',
       'event_cybersecurity_program', 'event_hs_info_session',
       'event_hs_campus_visit', 'event_individual_campus_visit',
       'event_workforce_class', 'event_corporate_training', 'event_teens_arts',
       'event_ccm_summer_camp', 'impact_hs_computing_class',
       'impact_hs_computing_club', 'impact_ap_computing_class',
       'impact_dual_enrollment', 'degree_program', 'motivation_job',
       'motivation_transfer_bachelors', 'motivation_transfer_hs',
       'motivation_career_advancement', 'motivation_career_change',
       'motivation_professional_dev', 'motivation_job_displacement',
       'motivation_relocation', 'motivation_keep_current',
       'motivation_certifications', 'motivation_financial',
       'motivation_enrichment', 'info_hs_counselor', 'info_hs_teacher',
       'info_ccm_website', 'info_ccm_admissions', 'info_ccm_advisor',
       'info_employer', 'info_ccm_workforce_development',
       'info_nj_workforce_development', 'info.other', 'gender', 'age'],
      dtype='object')

#### Find duplicates in data

In [59]:
duplicates = data.duplicated().sum()

In [60]:
duplicates

np.int64(0)

#### Taking out nAn values in the columns so I can understand the data better

In [61]:
data.head()

,timestamp,course_enrolled,hear_ccm_website,hear_social_media,hear_community_event,hear_family_friend,hear_current_student,hear_alumni,hear_hs_teacher,hear_hs_counselor,...,info_hs_teacher,info_ccm_website,info_ccm_admissions,info_ccm_advisor,info_employer,info_ccm_workforce_development,info_nj_workforce_development,info.other,gender,age
0,2024/09/09 12:33:58 PM AST,CMP 128 Computer Science I,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Man,21-24
1,2024/09/09 6:00:11 PM AST,NaN,No,No,Yes,No,No,No,Yes,Don't recall,...,Don't recall,No,No,No,No,No,No,Don't recall,Man,18 and younger
2,2024/09/10 9:00:12 AM AST,CMP 128 Computer Science I,No,No,No,Yes,No,Yes,No,Yes,...,No,No,Yes,No,No,No,No,No,Man,18 and younger
3,2024/09/10 12:34:53 PM AST,CMP 128 Computer Science I,Yes,Yes,Yes,Yes,No,No,Yes,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Man,19-20
4,2024/09/10 3:06:47 PM AST,CMP 128 Computer Science I,No,No,No,Yes,No,No,Yes,No,...,Don't recall,No,No,No,Yes,No,No,Yes,Man,19-20

In [62]:
motivationCols = ['motivation_relocation','motivation_keep_current', 'motivation_certifications','motivation_financial','motivation_enrichment']
data[motivationCols] = data[motivationCols].fillna('No Response')

In [63]:
infoCols = [col for col in data.columns if col.startswith('info_')]
data[infoCols] = data[infoCols].fillna('No Response')

In [64]:
data.columns

Index(['timestamp', 'course_enrolled', 'hear_ccm_website', 'hear_social_media',
       'hear_community_event', 'hear_family_friend', 'hear_current_student',
       'hear_alumni', 'hear_hs_teacher', 'hear_hs_counselor', 'hear_inapp_ad',
       'hear_employer', 'hear_billboard', 'hear_tv', 'hear_radio',
       'hear_other', 'event_open_house', 'event_instant_decision_day',
       'event_oncampus_info_session', 'event_titans_tuesday_virtual',
       'event_women_who_dare', 'event_college_fair',
       'event_hs_sharetime_session', 'event_challenger_program',
       'event_cybersecurity_program', 'event_hs_info_session',
       'event_hs_campus_visit', 'event_individual_campus_visit',
       'event_workforce_class', 'event_corporate_training', 'event_teens_arts',
       'event_ccm_summer_camp', 'impact_hs_computing_class',
       'impact_hs_computing_club', 'impact_ap_computing_class',
       'impact_dual_enrollment', 'degree_program', 'motivation_job',
       'motivation_transfer_bachelors', 'motivation_transfer_hs',
       'motivation_career_advancement', 'motivation_career_change',
       'motivation_professional_dev', 'motivation_job_displacement',
       'motivation_relocation', 'motivation_keep_current',
       'motivation_certifications', 'motivation_financial',
       'motivation_enrichment', 'info_hs_counselor', 'info_hs_teacher',
       'info_ccm_website', 'info_ccm_admissions', 'info_ccm_advisor',
       'info_employer', 'info_ccm_workforce_development',
       'info_nj_workforce_development', 'info.other', 'gender', 'age'],
      dtype='object')

In [65]:
data.head()

,timestamp,course_enrolled,hear_ccm_website,hear_social_media,hear_community_event,hear_family_friend,hear_current_student,hear_alumni,hear_hs_teacher,hear_hs_counselor,...,info_hs_teacher,info_ccm_website,info_ccm_admissions,info_ccm_advisor,info_employer,info_ccm_workforce_development,info_nj_workforce_development,info.other,gender,age
0,2024/09/09 12:33:58 PM AST,CMP 128 Computer Science I,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,...,No Response,No Response,No Response,No Response,No Response,No Response,No Response,NaN,Man,21-24
1,2024/09/09 6:00:11 PM AST,NaN,No,No,Yes,No,No,No,Yes,Don't recall,...,Don't recall,No,No,No,No,No,No,Don't recall,Man,18 and younger
2,2024/09/10 9:00:12 AM AST,CMP 128 Computer Science I,No,No,No,Yes,No,Yes,No,Yes,...,No,No,Yes,No,No,No,No,No,Man,18 and younger
3,2024/09/10 12:34:53 PM AST,CMP 128 Computer Science I,Yes,Yes,Yes,Yes,No,No,Yes,Yes,...,No Response,No Response,No Response,No Response,No Response,No Response,No Response,NaN,Man,19-20
4,2024/09/10 3:06:47 PM AST,CMP 128 Computer Science I,No,No,No,Yes,No,No,Yes,No,...,Don't recall,No,No,No,Yes,No,No,Yes,Man,19-20

#### Show data head and tail after it was cleaned to check difference

In [66]:
data.head()

,timestamp,course_enrolled,hear_ccm_website,hear_social_media,hear_community_event,hear_family_friend,hear_current_student,hear_alumni,hear_hs_teacher,hear_hs_counselor,...,info_hs_teacher,info_ccm_website,info_ccm_admissions,info_ccm_advisor,info_employer,info_ccm_workforce_development,info_nj_workforce_development,info.other,gender,age
0,2024/09/09 12:33:58 PM AST,CMP 128 Computer Science I,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,...,No Response,No Response,No Response,No Response,No Response,No Response,No Response,NaN,Man,21-24
1,2024/09/09 6:00:11 PM AST,NaN,No,No,Yes,No,No,No,Yes,Don't recall,...,Don't recall,No,No,No,No,No,No,Don't recall,Man,18 and younger
2,2024/09/10 9:00:12 AM AST,CMP 128 Computer Science I,No,No,No,Yes,No,Yes,No,Yes,...,No,No,Yes,No,No,No,No,No,Man,18 and younger
3,2024/09/10 12:34:53 PM AST,CMP 128 Computer Science I,Yes,Yes,Yes,Yes,No,No,Yes,Yes,...,No Response,No Response,No Response,No Response,No Response,No Response,No Response,NaN,Man,19-20
4,2024/09/10 3:06:47 PM AST,CMP 128 Computer Science I,No,No,No,Yes,No,No,Yes,No,...,Don't recall,No,No,No,Yes,No,No,Yes,Man,19-20

In [67]:
data.tail()

,timestamp,course_enrolled,hear_ccm_website,hear_social_media,hear_community_event,hear_family_friend,hear_current_student,hear_alumni,hear_hs_teacher,hear_hs_counselor,...,info_hs_teacher,info_ccm_website,info_ccm_admissions,info_ccm_advisor,info_employer,info_ccm_workforce_development,info_nj_workforce_development,info.other,gender,age
192,2024/09/22 6:32:46 PM AST,CMP 128 Computer Science I,Don't recall,Don't recall,Don't recall,Don't recall,Yes,Don't recall,Don't recall,Don't recall,...,No,No,No,No,No,No,No,No,Man,19-20
193,2024/09/22 8:51:18 PM AST,CMP 128 Computer Science I,Yes,No,No,Yes,No,No,No,Yes,...,Yes,Don't recall,Don't recall,Yes,Don't recall,Don't recall,Don't recall,Don't recall,Man,19-20
194,2024/09/22 9:17:23 PM AST,CMP 128 Computer Science I,Yes,Don't recall,No,No,No,No,Yes,Yes,...,No,Yes,Yes,Yes,No,No,No,No,Man,19-20
195,2024/09/22 11:07:28 PM AST,CMP 128 Computer Science I,Yes,No,No,Yes,Yes,Yes,Yes,No,...,Don't recall,Don't recall,Don't recall,Don't recall,Don't recall,Don't recall,Don't recall,Don't recall,Man,19-20
196,2024/09/27 1:01:23 PM AST,CMP 131 Fundamentals of Programming (Python),No,No,No,Yes,Yes,Yes,No,No,...,No,No,Yes,Yes,Yes,Yes,Yes,No,Man,25-34

In [68]:
#### Put data into a new cleaned csv file

In [69]:
data.to_csv('MajorSurveyResults24_cleaned_data.csv', index=False)

#### Citations: 
    ChatGPT - Renaming the columns
    https://saturncloud.io/blog/how-to-get-column-index-from-column-name-in-python-pandas/ - Getting column index